
-- data generated by datafiller.py version 2.0.0 (r792 on 2014-03-23) for postgresql

-- fill table person (100)
\echo # filling table person (100)
COPY person (persnr,vname,nname,geschlecht,gebdate) FROM STDIN (ENCODING 'utf-8');
90557	Catherine	Hailes	MW	2016-01-28
38354	Elwyn	Seagraves	MW	2016-03-21
86720	Akram	Lacoste	MW	2016-01-14
108540	Pittsburgh	Haire	MW	2016-02-22
77169	Charo	Glasser	MW	2016-03-14
48589	Vera	Qu	MW	2016-03-01
37951	Bobine	Talton	MW	2016-01-08
42216	Florry	Bourbonnais	MW	2016-02-18
61044	\N	Addetia	MW	2016-03-28
78673	Fan	Culp	MW	2016-02-18
50532	Maciej	Bannan	MW	2016-02-02
15608	Valerie	Egdorf	MW	2016-01-28
35840	Caprice	Harley	MW	2016-02-02
20529	Sile	Teacher	MW	2016-01-24
71216	Kristien	Schejbal	MW	2016-04-04
29930	Cesya	LaVecchia	MW	2016-01-20
102840	Herre	Zaydan	MW	2016-01-24
21936	Oper	Grund	MW	2016-04-06
97661	Skiclub	Ziegler	MW	2016-04-13
46679	Timmie	Korbel	MW	2016-02-19
18051	Kelsy	Dubroff	MW	2016-02-05
13889	Steffie	McKibbin	MW	2016-02-06
64146	Omar	Toscano	MW	2016-01-20
33121	Ede	\N	MW	2016-03-18
27467	Barbe	Maheux	MW	2016-01-30
106836	Weilin	Craddock	MW	2016-03-18
74395	Leelah	Bohanan	MW	2016-03-27
108713	Myrlene	Storey	MW	2016-03-27
18725	Raychel	Marette	MW	2016-02-10
94240	Madelle	Gungor	MW	2016-03-27
106155	Kaile	Ramey	MW	2016-02-03
57850	Eolanda	Mucci	MW	2016-03-24
51612	Tuesday	Marcellus	MW	2016-03-11
85330	Cornela	Knieps	MW	2016-04-02
101453	Loralie	Bulkovshteyn	MW	2016-03-24
11432	Logntp	\N	MW	2016-03-08
20436	Priscella	Amir	MW	2016-01-31
53903	Tatsuya	David-Yerumo	MW	2016-01-12
71395	Hanns	Frondozo	MW	2016-04-14
108817	Tomasz	Hartman	MW	2016-02-08
29110	\N	Ayrault	MW	2016-02-01
54356	Gen	Esselbach	MW	2016-03-28
100778	Elisabetta	Ghani	MW	2016-02-06
71288	Nanette	Hadden	MW	2016-03-11
98461	Brunhilde	Bresnahan	MW	2016-03-17
19922	Dwain	Cobb	MW	2016-02-07
45759	Trenna	Benjamin	MW	2016-02-08
33073	Ranice	Stephen	MW	2016-03-10
65719	Thakor	Tucker	MW	2016-03-20
72843	Kas	Twolan	MW	2016-03-09
70299	Jilleen	Tougas	MW	2016-01-30
65042	Bambi	Myatt	MW	2016-02-07
21163	Becka	Bartolucci	MW	2016-02-20
16964	Fiona	Montuno	MW	2016-03-03
102420	Stock	Szkarlat	MW	2016-04-15
82784	Hulst	Huszarik	MW	2016-02-21
29270	Spiros	Owens	MW	2016-03-25
13264	Jobie	Trinidad	MW	2016-04-05
70192	Gayle	Cioffi	MW	2016-03-01
34015	Biplab	Cosner	MW	2016-02-22
17211	Anette	Ballard	\N	2016-03-04
104779	Rchisn	Driedger	MW	2016-01-30
58916	Biplab	Gillespie	MW	2016-03-13
52151	Tallulah	Scrivens	MW	2016-03-10
93102	Madelyn	Hardage	MW	2016-01-18
33784	Charmaine	Marco	MW	2016-04-11
83782	Budi	Perrier	MW	2016-04-14
78878	Elbert	Rance	MW	2016-04-14
46036	Sharyl	Underwood	MW	2016-03-31
80655	Reta	Marshman	MW	2016-01-25
53293	Chip	Hogeboom	MW	2016-01-08
36302	Doortje	Deininger	MW	2016-04-05
73119	Hope	Cullipher	MW	2016-02-05
76954	Naim	Kurio	MW	2016-02-05
100192	Heidi	Yuill	MW	2016-01-14
75659	Winnah	Seifers	MW	2016-02-21
55075	Rui-Yuan	Kuehn	MW	2016-03-01
102311	Amrik	Maccallum	MW	2016-02-08
51801	Saundra	Tencer	MW	2016-03-20
41335	Nirmal	Floysvik	MW	2016-03-28
109942	Reba	Ruth	MW	2016-02-08
92012	Dorita	Hartleb	MW	2016-02-25
58317	Alfonzo	Lecandro	MW	2016-03-10
92699	Dawna	Hammond	MW	2016-02-14
81890	Gerardo	Trainer	MW	2016-03-08
22501	Maryanne	Davis	MW	2016-01-08
63432	Levent	Markovich	MW	2016-01-09
63674	Moniek	Bronec	MW	2016-01-24
78462	Bert	Cholewinski	MW	2016-04-15
105714	Deva	Glover	MW	2016-01-26
15496	Amberly	Goins	MW	2016-03-29
49105	Amarjit	Narraway	MW	2016-01-17
103923	Selle	Klug	MW	2016-02-22
28547	Darell	Felton	MW	2016-02-25
30559	Quintana	Langley	MW	2016-02-09
88079	Bobbye	Phalpher	MW	2016-01-16
71707	Aili	Nearing	MW	2016-04-14
30024	Belleville	Verification	MW	2016-01-15
109536	Hana	Godowsky	MW	2016-01-20
76732	Jere	Cinar	MW	2016-04-07
\.

-- restart sequences
ALTER SEQUENCE person_persnr_seq RESTART WITH 109999;

-- analyze modified tables
ANALYZE person;
