
-- data generated by datafiller.py version 2.0.0 (r792 on 2014-03-23) for postgresql

-- fill table person (100)
\echo # filling table person (100)
COPY person (persnr,vname,nname,geschlecht,gebdate) FROM STDIN (ENCODING 'utf-8');
38085	Dorolice	Andreatos	W	2016-04-15
93847	Yeung	Aghi	W	2016-03-27
47572	Duryonna	Baudais	W	2016-01-26
58732	Valida	Brocato	M	2016-03-03
15504	Kitt	\N	W	2016-01-11
35588	Wallis	Hubers	W	2016-03-01
53030	Baris	Hurtubise	W	2016-02-18
57947	Florence	Janiszewski	W	2016-04-10
23597	Corenda	Bankhead	M	2016-03-12
18549	Netas	Spinks	W	2016-03-14
51223	Emylee	Zajac	W	2016-03-13
99872	Timm	Murdaugh	W	2016-01-28
106803	Olympe	Coulson	W	2016-03-31
108014	Dorthy	Vradmin	M	2016-01-19
59169	Avinash	Glaser	W	2016-04-06
109958	Riyaz	Kirby	W	2016-02-11
72742	Marna	Furlow	M	2016-01-09
73560	Jozsef	Scholey	M	2016-04-10
69252	Fadi	Salim-Yasuda	M	2016-04-12
45872	Biddy	Naguib	W	2016-01-22
97110	Dickens	Mitchelson	M	2016-02-06
21623	Alica	Shrieves	W	2016-01-14
68759	\N	Fastfeat	W	2016-02-24
10128	Cordula	Isaac	M	2016-04-11
71349	DeAnne	Spence	M	2016-04-06
52447	Katalin	Riley	M	2016-02-29
42348	Charissa	Yeck	M	2016-03-01
22306	Amaleta	Karam	M	2016-02-11
57164	Drago	Korbe	M	2016-03-08
95264	Fidelia	Garinger	W	2016-04-04
22091	Dpnlab	Fouret	W	2016-03-29
25737	Rogelio	Bowles	W	2016-03-30
65180	Georges	Nassr	M	2016-03-17
38082	Alica	Frierson	M	2016-02-16
108487	Leni	Procner	W	2016-02-03
88015	Yovonnda	Bashyam	M	2016-01-23
106078	Lucia	Langelier	W	2016-04-12
101850	Bernardo	Hodgens	M	2016-03-02
55772	Lucina	Gagnier	M	2016-02-25
88614	Mimi	Javallas-Ross	M	2016-04-03
99160	Pollyanna	\N	W	2016-04-08
60634	Reine	Weatherly	M	2016-03-18
12040	Eleonore	Adorno	W	2016-03-11
42731	Synful	Wheelock	W	2016-02-20
69575	Alexina	Szabo	W	2016-02-26
36620	Celestia	Panchmatia	W	2016-02-05
95729	Achal	McBroom	W	2016-02-22
94522	Yuen	Buder	W	2016-03-24
74675	Mellisa	Pulver	W	2016-03-19
94465	Arvind	Biedermann	W	2016-02-19
48916	Mattie	Britton	M	2016-04-03
69032	Kim-Minh	Congdon	W	2016-04-10
16081	Terrell	Rangooni	W	2016-01-28
18410	Merb	Russett	M	2016-02-27
32818	Carita	Jahromi	M	2016-01-12
64610	Willow	Degan	W	2016-03-23
48382	Laurianne	Azer	W	2016-02-11
45755	Jessika	Klimon	W	2016-02-13
68701	Charley	Schesvold	W	2016-01-07
44023	Halimeda	Rickard	M	2016-02-17
66583	Jeff	Jagatic	M	2016-02-26
23519	Mohammad	Adhem	M	2016-01-23
49171	Brand	Livshits	M	2016-01-10
75163	Katrina	Beresnikow	W	2016-02-04
109334	Kathy	Demchuk	W	2016-01-31
50036	Walliw	McClean	M	2016-02-03
80167	Edlene	Payn	M	2016-01-23
57423	Row	Dall oste	M	2016-03-21
28441	Mavra	Sprigings	W	2016-02-04
15818	Vilhelm	Escher	W	2016-03-04
95592	Omar	Jubenville	M	2016-03-03
47572	Asghar	Xayaraj	M	2016-02-09
28753	Rosalyn	Dobbing	M	2016-03-24
64329	Calypso	Tye	M	2016-02-06
71637	Yeung	Mizerk	W	2016-02-17
38993	Darrel	Calmejane	W	2016-01-13
97277	Babette	Wark	M	2016-03-19
18967	Aly	Samhaber	M	2016-04-08
86366	Sela	Mcginley	W	2016-03-27
84336	Maisie	Raine	M	2016-03-11
98037	Carlo	Boggild	W	2016-02-17
21314	Debbi	Brown-Gillard	M	2016-01-21
28979	Wynn	Hermanns	W	2016-04-04
29544	Malina	Cinicolo	M	2016-02-25
13529	Sue-May	Stars	M	2016-01-17
38081	Edmx	Canuel	M	2016-03-08
47529	Meer	Wicht	M	2016-03-14
36530	Sidonia	Robieux	M	2016-01-20
38335	Asmar	Hunike	W	2016-04-12
66058	Jess	Glasser	M	2016-03-01
87615	Berneta	McCorquodale	W	2016-02-02
35537	Anatoli	Couto	M	2016-01-13
20226	Chitra	Buggie	W	\N
18526	Hrinfo	Condurelis	M	2016-02-23
101924	Cleo	Khalaf	M	2016-03-08
41253	Edel	Morgan	M	2016-02-05
98386	Bryant	Carranza	W	2016-03-18
57180	Freddie	Jankowski	W	2016-02-14
80455	Idalia	Collins	W	2016-01-26
69116	Code	Brookes	W	2016-03-27
\.

-- restart sequences
ALTER SEQUENCE person_persnr_seq RESTART WITH 109999;

-- analyze modified tables
ANALYZE person;
